name: flutter_monitores
description: Aplicativo Flutter com carrossel de cards dos monitores do DPD.

# Versão do SDK Flutter
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0            # Atualizado para a última versão
  firebase_core: ^3.6.0               # Atualizado para a última versão
  firebase_database: ^11.1.4           # Atualizado para a última versão

# Dependências para desenvolvimento (ex.: linter)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0               # Atualizado para a última versão
  lints: ^4.0.0                        # Atualizado para a última versão

flutter:
  uses-material-design: true

  # Caminho para as imagens do aplicativo (se necessário)
  # assets:
  #  - assets/images/
